version: '3.8'
services:
 mongo:
   image: mongo
   container_name: medease-mongo
   restart: always
   ports:
     - "27017:27017"
   environment:
     MONGO_INITDB_ROOT_USERNAME: admin
     MONGO_INITDB_ROOT_PASSWORD: ArshadCMP216pass
 app:
   build: .
   container_name: medease-app
   restart: always
   ports:
     - "3000:3000"
   env_file:
     - .env
   volumes:
     - .:/app
   depends_on:
     - mongo